In [1]:
from google.colab import drive
drive.mount('/content/drive/')


Mounted at /content/drive/


In [3]:
import os
os.chdir('/content/drive/MyDrive/satellite-altimetry-course')


In [4]:
# !pip install cartopy
# !pip install pyrsimg
# !apt-get install hdf5-tools


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 37.6 MB/s eta 0:00:00
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  hdf5-tools
0 upgraded, 1 newly installed, 0 to remove and 45 not upgraded.
Need to get 347 kB of archives.
After this operation, 1,255 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 hdf5-tools amd64 1.10.7+repack-4ubuntu2 [347 kB]
Fetched 347 kB in 1s (529 kB/s)
Selecting previously unselected package hdf5-tools.
(Reading database ... 121918 files and directories currently installed.)
Preparing to unpack .../hdf5-tools_1.10.7+repack-4ubuntu2_amd64.deb ...
Unpacking hdf5-tools (1.10.7+repack-4ubuntu2) ...
Setting up hdf5-tools (1.10.7+repack-4ubuntu2) ...
Processing triggers for man-db (2.10.2-1) ...


In [10]:
import h5py
import numpy as np
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
from pyrsimg import readTiff, imgShow, second_to_dyr



In [6]:
path_atl06 = 'data/laser/processed_ATL06_20200806013350_06370802_006_01.h5'
path_rsimg = 'data/rsimg/s2_gla_region_20220707.tif'



In [41]:
!h5ls $path_atl06/gt1l/land_ice_segments/atl06_quality_summary


atl06_quality_summary    Dataset {1890/Inf}


In [46]:
vars_atl06 = {}
beams = ['gt1l','gt1r','gt2l','gt2r','gt3l','gt3r',]
with h5py.File(path_atl06, 'r') as atl06:
    for beam in beams:
        vars_atl06['lat_'+beam] = atl06[beam+'/land_ice_segments/latitude'][:]
        vars_atl06['lon_'+beam] = atl06[beam+'/land_ice_segments/longitude'][:]
        vars_atl06['elev_'+beam] = atl06[beam+'/land_ice_segments/h_li'][:]
        vars_atl06['time_delta_'+beam] = atl06[beam+'/land_ice_segments/delta_time'][:]
        ### 质量
        vars_atl06['qual_'+beam] = atl06[beam+'/land_ice_segments/atl06_quality_summary'][:]
        vars_atl06['cycle'] = atl06['orbit_info/cycle_number'][0]
        vars_atl06['track'] = atl06['orbit_info/rgt'][0]
        vars_atl06['orient'] = atl06['orbit_info/sc_orient'][0]

rsimg = readTiff(path_rsimg)


In [47]:
vars_atl06['qual_'+beam]


array([1, 1, 1, ..., 0, 0, 0], dtype=int8)

In [51]:
region = [94.56, 30.38, 95.04, 30.77]
processed_vars_atl06 = {}
for beam in beams:
    ids_beam = np.where((vars_atl06['lat_'+beam]>region[1]) \
                & (vars_atl06['lat_'+beam]<region[3])\
                & (vars_atl06['lon_'+beam]>region[0])\
                & (vars_atl06['lon_'+beam]<region[2])\
                & (vars_atl06['elev_'+beam]<9000)\
                & (vars_atl06['qual_'+beam]==0) )[0]
    print(ids_beam.shape)
    processed_vars_atl06['lat_'+beam] = vars_atl06['lat_'+beam][ids_beam]
    processed_vars_atl06['lon_'+beam] = vars_atl06['lon_'+beam][ids_beam]
    processed_vars_atl06['elev_'+beam] = vars_atl06['elev_'+beam][ids_beam]
    processed_vars_atl06['time_delta_'+beam] = vars_atl06['time_delta_'+beam][ids_beam]


(1114,)
(505,)
(749,)
(450,)
(911,)
(540,)


In [54]:
print(vars_atl06['lat_gt2r'].shape)
print(processed_vars_atl06['lat_gt1r'].shape)


(1796,)
(505,)


In [56]:
processed_vars_atl06['cycle'] = vars_atl06['cycle']
processed_vars_atl06['track'] = vars_atl06['cycle']
processed_vars_atl06['orient'] = vars_atl06['orient']


In [58]:
processed_vars_atl06['time_delta_'+beam][0:5]


array([81912883.87333229, 81912883.87616834, 81912883.9608879 ,
       81912883.96371189, 81912883.96653393])

In [59]:
for beam in beams:
    processed_vars_atl06['time_dyr_'+beam] = second_to_dyr(processed_vars_atl06['time_delta_'+beam], \
                                time_start='2018-01-01 00:00:00')


In [60]:
processed_vars_atl06['time_dyr_'+beam][0:5]


array([2020.59580933, 2020.59580933, 2020.59580933, 2020.59580933,
       2020.59580933])

In [63]:
file_out = 'data/laser/isat2_gla_region.h5'
with h5py.File(file_out, 'w') as f_out:
    [f_out.create_dataset(key, data=processed_vars_atl06[key]) for key in processed_vars_atl06.keys()]
